# If you come from bash you might have to change your $PATH.
export PATH=/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="juanghurtado"
KEYTIMEOUT=1

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# DISABLE_UPDATE_PROMPT="true"
# HIST_STAMPS="mm/dd/yyyy"
#
HISTSIZE=1000
SAVEHIST=1000
plugins=(hub git-flow docker vi-mode)
source $ZSH/oh-my-zsh.sh
# Zsh and the fuck
eval "$(direnv hook zsh)"
eval "$(hub alias -s)"
eval "$(thefuck --alias)"
setopt HIST_IGNORE_ALL_DUPS
export PGDATA=$HOME/Lib/Data/pgsql
export PGLOG=$HOME/Lib/Data/log/pglog
export HOMEBREW_GITHUB_API_TOKEN="534bb1e8bfc5f6f2f6789d4ae48a6b4b5c4657ee"
export NVM_DIR="$HOME/.nvm"
alias loadnode='[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
alias nig='npm install -g'
alias ni='npm install'
alias nip='npm install --production'
alias tm='tmux -2'
alias supervisorctl='supervisorctl -c /usr/local/etc/supervisord.ini'
alias python='/usr/local/bin/python2'
alias vim='nvim'
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2
source /usr/local/bin/virtualenvwrapper.sh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
