#!/bin/bash


BASE=$(pwd)
VIMBASE="${BASE}"/editor/vim
TMUXCONF="${BASE}"/shell/tmux/tmux.conf
VIMRC=${VIMBASE}/editor/vim/
DISTVIMRC=$HOME/.vimrc

install_tmux() {
  echo "install tmux"
  if [[ $(command -v tmux) == "" ]];then
    echo TMUX not installed, install for you now
    brew install tmux
  else
    echo TMUX had be installed
  fi
  ln -sf ${TMUXCONF} ${HOME}/.tmux.conf
  echo "installed tmux config done"
}


install_zsh() {
  echo 'Install zsh config'
  ln -sf $BASE/shell/zsh/zshrc    $HOME/.zshrc
  ln -sf $BASE/shell/zsh/zshenv   $HOME/.zshenv
  ln -sf $BASE/shell/zsh/zprofile $HOME/.zprofile
  ln -sf $BASE/shell/zsh/themes/* $HOME/.oh-my-zsh/custom/themes/
}


main() {
  install_tmux
  install_zsh
}

main
