#######################################
############# Alias settings ##########
#######################################
alias clone='hub clone'
alias swagger="docker run --rm -it -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
alias gc="git clone"
alias gp="git push"
alias gu="git pull"
alias gl="git lg"
alias gs="git status"
alias dc='docker-compose'
alias spd='supervisord -c /usr/local/etc/supervisord.ini'
alias spc='supervisorctl -c /usr/local/etc/supervisord.ini'
alias ni='npm i'
alias nip='npm i --production'
alias h='tldr'
alias pull="hub pull"

### docker alias
alias dctn='docker container'
alias dimg='docker image'
alias dnet='docker network'
alias dplg='docker plugin'
alias dcheck='docker checkpoint'
alias dsev='docker service'
alias dswarm='docker swarm'
alias dstack='docker stack'
alias dmachine='docker-machine'

#### docker network
alias dnet-new='docker network create'
alias dnet-list='docker network ls'
alias dnet-del='docker network rm'
alias dnet-info='docker network inspect'
alias dnet-clean='docker network prune'
alias dnet-conn='docker netwrok connect'
alias dnet-dis='docker network disconnect'

### docker image
alias dimg-list='dimg ls'
alias dimg-history='dimg history'
alias dimg-build='dimg build'
alias dimg-load='dimg load'
alias dimg-clean='dimg prune'
alias dimg-get='dimg pull'
alias dimg-tag='dimg tag'
alias dimg-info='dimg inspect'
alias dimg-upload='dimg push'
alias dimg-from='dimg import'

### docker container
alias dctn-list='dctn ls'
alias dctn-cp='dctn cp'
alias dctn-diff='dctn-diff'
alias dctn-ports='dctn port'
alias dctn-kill='dctn kill'
alias dctn-clean='dctn prune -f'
alias dctn-start='dctn start'
alias dctn-stop='dctn stop'
alias dctn-info='dctn stats'
alias dctn-attach='dctn attach'
alias dctn-into='dctn exec -it'
alias dctn-new-daemon='dctn run -d'
alias dctn-new-it='dctn run -it'
alias dctn-new-it-tmp='dctn run -it --rm'

# docker-curl talk to docker use curl
alias curl-docker='curl -s --unix-socket /var/run/docker.sock'

# youtube-dl
alias ydl='docker run --rm vimagick/youtube-dl'

# common
alias update='. $HOME/.zshrc && . $HOME/.zshenv && . $HOME/.zprofile'
alias tm='tmux -2'
alias cat='ccat'
alias ax='axel -n 10'

# nvm
alias loadnvm="[ -s $NVM_DIR/nvm.sh ] && . $NVM_DIR/nvm.sh"

function vim() {
    if type nvim &>/dev/null; then
        nvim "$@"
    else
        vim "$@"
    fi
}

# if type vim &>/dev/null ;then
# 	alias vim="nvim"
# fi

# lazydocker
alias lzd='lazydocker'

# node
alias nt='npm test'
alias ni='npm install'
alias nip='npm install --production'

# ft editor
alias -s {yml,yaml,json,md,markdown,toml}=vim

# change dir
alias d='dirs -v | head -10'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

# minio client - mc
# alias mc="docker run --rm -it --link minio:minio minio/mc"
