# If you come from bash you might have to change your $PATH.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="lambda"


DISABLE_AUTO_UPDATE="true"


export UPDATE_ZSH_DAYS=13


COMPLETION_WAITING_DOTS="true"

plugins=(
	ansible
	git
	go
	gas
	wd
	github
	docker
	docker-compose
	zsh-autosuggestions
	git-extras
	git-flow
	kubectl
	helm
)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export EDITOR="emacs"
