# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/Cheerfyt/.oh-my-zsh
ZSH_THEME="robbyrussell"
ENABLE_CORRECTION="true"
plugins=(git hub git-flow wd docker docker-compose z zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh


##
alias refresh='source $HOME/.zshrc'
alias untar='tar -xzvf $1'
alias supervisorctl='supervisorctl -c /usr/local/etc/supervisord.ini'
alias tm='tmux -2'
alias cat='ccat'

export LANG=en_US.UTF-8
eval "$(direnv hook zsh)"
export PATH=$HOME/go/bin:$PATH

## python virtualenvwrpper
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2
. /usr/local/bin/virtualenvwrapper.sh
export LC_ALL="en_US.UTF-8"
export PATH=$PATH:$HOME/kubernetes/client/bin
